### ISSUE TITLE
Implement metadata

### ISSUE THREAD

**Issue by vteague** [DemocracyDevelopers/raire-service#40]
After completion of #38, implement a metadata class that contains the information that we intend to give to the assertion visualiser. This should include at least:
- contest (name)
- Candidate names
- riskLimit
- array of assertion risks
- RAIRE solution or error

Write a constructor that builds it, either (as default) from each field separately, or (perhaps better) from the GetAssertionRequest (which has the candidate names, contest name and risk limit).

Note that the riskLimit and array of assertion risks are _not_ relevant to the generate-and-get-assertions case - think about how to make these optional. 

Implement tests. These will be pretty trivial because it's really just a constructor.

**Comment by michelleblom** [comment]
Vanessa completed this card.
