### ISSUE TITLE
Establish a format for logs and add logging statements throughout.

### ISSUE THREAD

**Issue by vteague** [DemocracyDevelopers/raire-service#60]
Decide on log format and add consistent logging statements.

Consider proper formatting and info for error, debug and info logs.
Figure out how to configure the slf4j loggerfactory to produce logs with the required info in required format.

Note that the current default config used by ContestRequest contains all the useful info we need, but the formatting isn't ideal. 

An example error log message from that default setting is: 
```
2024-04-05T15:27:21.424+11:00 ERROR 20484 --- [           main] a.o.d.r.request.ContestRequest           : No contest name.
```
which is sort of fine, but it doesn't say [raire-service] and it has a lot of useless whitespace.

**Comment by michelleblom** [comment]
We have opted for: 

[method-name] Log text

for our log messages, class name will automatically appear in the prefix to "[method-name] Log Text".

When calling repository methods (that form SQL queries), we will log the call and the arguments to the call. 

Log statements should be applied at least on entry/exit of methods.

Make logging statements as descriptive as possible.

**Comment by vteague** [comment]
Done by #80
